<a href="https://colab.research.google.com/github/suseenthiran11c/CRIC/blob/master/ipl_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install -q snowflake-connector-python

In [7]:
from google.colab import userdata

print("User:", userdata.get("SNOWFLAKE_USER"))
print("Account:", userdata.get("SNOWFLAKE_ACCOUNT"))
print("Warehouse:", userdata.get("SNOWFLAKE_WAREHOUSE"))

print("Password secret exists:",
      bool(userdata.get("SNOWFLAKE_PASSWORD")))

User: SUSEENTHIRAN
Account: XSDGKEL-VB66962
Warehouse: TECH
Password secret exists: True

In [8]:
import snowflake.connector
from google.colab import userdata

conn = snowflake.connector.connect(
    user=userdata.get("SNOWFLAKE_USER"),
    password=userdata.get("SNOWFLAKE_PASSWORD"),
    account=userdata.get("SNOWFLAKE_ACCOUNT"),
    warehouse=userdata.get("SNOWFLAKE_WAREHOUSE"),
    database="NLP2SQL",
    schema='"test schema"',
    role="ACCOUNTADMIN"
)

print("✅ Snowflake connected successfully!")

✅ Snowflake connected successfully!

In [9]:
cursor = conn.cursor()

cursor.execute("""
SELECT CURRENT_USER(), CURRENT_DATABASE(), CURRENT_SCHEMA(), CURRENT_WAREHOUSE()
""")

print(cursor.fetchone())

('SUSEENTHIRAN', 'NLP2SQL', 'test schema', None)

In [10]:
cursor.execute("""
SELECT COUNT(*)
FROM NLP2SQL."test schema".IPLMATCHS
""")

count = cursor.fetchone()[0]

print("Total IPL matches:", count)

Total IPL matches: 1169

In [14]:
cursor = conn.cursor()

cursor.execute("SHOW WAREHOUSES")

warehouses = cursor.fetchall()

for w in warehouses:
    print(w[0])

COMPUTE_WH
SNOWFLAKE_LEARNING_WH
SYSTEM$STREAMLIT_NOTEBOOK_WH

In [15]:
cursor = conn.cursor()

cursor.execute("USE WAREHOUSE COMPUTE_WH")

print("✅ COMPUTE_WH selected")

✅ COMPUTE_WH selected

In [16]:
cursor.execute("SELECT CURRENT_WAREHOUSE()")

print("Active warehouse:", cursor.fetchone()[0])

Active warehouse: COMPUTE_WH

In [17]:
import pandas as pd

query = """
SELECT
    MATCH_ID,
    SEASON_ID,
    TEAM1,
    TEAM2,
    CITY,
    VENUE,
    TOSS_WINNER,
    TOSS_DECISION,
    MATCH_WINNER,
    RESULT,
    MATCH_TYPE,
    STAGE
FROM NLP2SQL."test schema".IPLMATCHS
"""

cursor.execute(query)

rows = cursor.fetchall()
columns = [col[0] for col in cursor.description]

df = pd.DataFrame(rows, columns=columns)

print("✅ IPL data loaded successfully!")
print("Total rows:", len(df))
print("Columns:", df.columns.tolist())

df.head(10)

✅ IPL data loaded successfully!
Total rows: 1169
Columns: ['MATCH_ID', 'SEASON_ID', 'TEAM1', 'TEAM2', 'CITY', 'VENUE', 'TOSS_WINNER', 'TOSS_DECISION', 'MATCH_WINNER', 'RESULT', 'MATCH_TYPE', 'STAGE']

,MATCH_ID,SEASON_ID,TEAM1,TEAM2,CITY,VENUE,TOSS_WINNER,TOSS_DECISION,MATCH_WINNER,RESULT,MATCH_TYPE,STAGE
0,335982,2008,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,win,league match,None
1,1082591,2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,field,Sunrisers Hyderabad,win,league match,None
2,1082592,2017,Rising Pune Supergiant,Mumbai Indians,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Rising Pune Supergiant,win,league match,None
3,1082593,2017,Gujarat Lions,Kolkata Knight Riders,Rajkot,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,win,league match,None
4,1082594,2017,Punjab Kings,Rising Pune Supergiant,Indore,Holkar Cricket Stadium,Punjab Kings,field,Punjab Kings,win,league match,None
5,1082595,2017,Royal Challengers Bangalore,Delhi Capitals,Bengaluru,M.Chinnaswamy Stadium,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,win,league match,None
6,1082596,2017,Sunrisers Hyderabad,Gujarat Lions,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,field,Sunrisers Hyderabad,win,league match,None
7,1082597,2017,Mumbai Indians,Kolkata Knight Riders,Mumbai,Wankhede Stadium,Mumbai Indians,field,Mumbai Indians,win,league match,None
8,1082598,2017,Punjab Kings,Royal Challengers Bangalore,Indore,Holkar Cricket Stadium,Royal Challengers Bangalore,bat,Punjab Kings,win,league match,None
9,1082599,2017,Rising Pune Supergiant,Delhi Capitals,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Capitals,win,league match,None

In [18]:
print("Shape:", df.shape)

print("\nFirst 10 rows:")
display(df.head(10))

print("\nColumn information:")
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())

print("\nMatch winners:")
print(df["MATCH_WINNER"].value_counts())

Shape: (1169, 12)

First 10 rows:

,MATCH_ID,SEASON_ID,TEAM1,TEAM2,CITY,VENUE,TOSS_WINNER,TOSS_DECISION,MATCH_WINNER,RESULT,MATCH_TYPE,STAGE
0,335982,2008,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,Kolkata Knight Riders,win,league match,None
1,1082591,2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,field,Sunrisers Hyderabad,win,league match,None
2,1082592,2017,Rising Pune Supergiant,Mumbai Indians,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Rising Pune Supergiant,win,league match,None
3,1082593,2017,Gujarat Lions,Kolkata Knight Riders,Rajkot,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,field,Kolkata Knight Riders,win,league match,None
4,1082594,2017,Punjab Kings,Rising Pune Supergiant,Indore,Holkar Cricket Stadium,Punjab Kings,field,Punjab Kings,win,league match,None
5,1082595,2017,Royal Challengers Bangalore,Delhi Capitals,Bengaluru,M.Chinnaswamy Stadium,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,win,league match,None
6,1082596,2017,Sunrisers Hyderabad,Gujarat Lions,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,field,Sunrisers Hyderabad,win,league match,None
7,1082597,2017,Mumbai Indians,Kolkata Knight Riders,Mumbai,Wankhede Stadium,Mumbai Indians,field,Mumbai Indians,win,league match,None
8,1082598,2017,Punjab Kings,Royal Challengers Bangalore,Indore,Holkar Cricket Stadium,Royal Challengers Bangalore,bat,Punjab Kings,win,league match,None
9,1082599,2017,Rising Pune Supergiant,Delhi Capitals,Pune,Maharashtra Cricket Association Stadium,Rising Pune Supergiant,field,Delhi Capitals,win,league match,None

Column information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MATCH_ID       1169 non-null   int64
 1   SEASON_ID      1169 non-null   int64
 2   TEAM1          1169 non-null   object
 3   TEAM2          1169 non-null   object
 4   CITY           1169 non-null   object
 5   VENUE          1169 non-null   object
 6   TOSS_WINNER    1168 non-null   object
 7   TOSS_DECISION  1168 non-null   object
 8   MATCH_WINNER   1161 non-null   object
 9   RESULT         1169 non-null   object
 10  MATCH_TYPE     1169 non-null   object
 11  STAGE          4 non-null      object
dtypes: int64(2), object(10)
memory usage: 109.7+ KB
None

Missing values:
MATCH_ID            0
SEASON_ID           0
TEAM1               0
TEAM2               0
CITY                0
VENUE               0
TOSS_WINNER         1
TOSS_DECISION       1
MATCH_WINNER        8
RESULT              0
MATCH_TYPE          0
STAGE            1165
dtype: int64

Match winners:
MATCH_WINNER
Mumbai Indians                 153
Chennai Super Kings            142
Kolkata Knight Riders          135
Royal Challengers Bangalore    133
Sunrisers Hyderabad            125
Punjab Kings                   123
Delhi Capitals                 121
Rajasthan Royals               116
Gujarat Titans                  37
Lucknow Super Giants            30
Rising Pune Supergiant          15
Gujarat Lions                   13
Pune Warriors                   12
Kochi Tuskers Kerala             6
Name: count, dtype: int64

In [19]:
# Remove rows where important ML fields are missing

df = df.dropna(
    subset=[
        "TEAM1",
        "TEAM2",
        "VENUE",
        "TOSS_WINNER",
        "TOSS_DECISION",
        "MATCH_WINNER"
    ]
).copy()

print("✅ Data cleaned successfully!")
print("Remaining rows:", len(df))
print("Missing values:")
print(df[
    [
        "TEAM1",
        "TEAM2",
        "VENUE",
        "TOSS_WINNER",
        "TOSS_DECISION",
        "MATCH_WINNER"
    ]
].isnull().sum())

✅ Data cleaned successfully!
Remaining rows: 1161
Missing values:
TEAM1            0
TEAM2            0
VENUE            0
TOSS_WINNER      0
TOSS_DECISION    0
MATCH_WINNER     0
dtype: int64

In [20]:
features = [
    "TEAM1",
    "TEAM2",
    "VENUE",
    "TOSS_WINNER",
    "TOSS_DECISION"
]

X = df[features].copy()
y = df["MATCH_WINNER"].copy()

print("✅ Features and target prepared!")

print("\nFeatures:")
print(X.head())

print("\nTarget:")
print(y.head())

✅ Features and target prepared!

Features:
                         TEAM1                        TEAM2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders
1          Sunrisers Hyderabad  Royal Challengers Bangalore
2       Rising Pune Supergiant               Mumbai Indians
3                Gujarat Lions        Kolkata Knight Riders
4                 Punjab Kings       Rising Pune Supergiant

                                       VENUE                  TOSS_WINNER  \
0                      M Chinnaswamy Stadium  Royal Challengers Bangalore
1  Rajiv Gandhi International Stadium, Uppal  Royal Challengers Bangalore
2    Maharashtra Cricket Association Stadium       Rising Pune Supergiant
3     Saurashtra Cricket Association Stadium        Kolkata Knight Riders
4                     Holkar Cricket Stadium                 Punjab Kings

  TOSS_DECISION
0         field
1         field
2         field
3         field
4         field

Target:
0     Kolkata Knight Riders
1       Sunrisers Hyderabad
2    Rising Pune Supergiant
3     Kolkata Knight Riders
4              Punjab Kings
Name: MATCH_WINNER, dtype: object

In [21]:
from sklearn.preprocessing import LabelEncoder

# Store an encoder for each feature
encoders = {}

for column in features:
    encoder = LabelEncoder()
    X[column] = encoder.fit_transform(X[column].astype(str))
    encoders[column] = encoder

# Encode the target (MATCH_WINNER)
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y.astype(str))

print("✅ Encoding completed!")

print("\nEncoded features:")
print(X.head())

print("\nEncoded target:")
print(y[:10])

print("\nTeams/classes:")
print(list(target_encoder.classes_))

✅ Encoding completed!

Encoded features:
   TEAM1  TEAM2  VENUE  TOSS_WINNER  TOSS_DECISION
0     12      5     23           12              1
1     13     12     43           12              1
2     11      7     31           11              1
3      2      5     46            5              1
4      9     11     20            9              1

Encoded target:
[ 5 13 11  5  9 12 13  7  9  1]

Teams/classes:
['Chennai Super Kings', 'Delhi Capitals', 'Gujarat Lions', 'Gujarat Titans', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("✅ Data split completed!")

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Training target:", len(y_train))
print("Testing target:", len(y_test))

✅ Data split completed!
Training samples: 928
Testing samples: 233
Training target: 928
Testing target: 233

In [23]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced"
)

model.fit(X_train, y_train)

print("✅ Random Forest model trained successfully!")

✅ Random Forest model trained successfully!

In [24]:
from sklearn.metrics import accuracy_score

# Make predictions on test data
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("✅ Prediction completed!")
print("Model Accuracy:", round(accuracy * 100, 2), "%")

✅ Prediction completed!
Model Accuracy: 51.5 %

In [25]:
from sklearn.metrics import classification_report

print("Classification Report:\n")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=target_encoder.classes_,
        zero_division=0
    )
)

Classification Report:

                             precision    recall  f1-score   support

        Chennai Super Kings       0.48      0.45      0.46        29
             Delhi Capitals       0.41      0.38      0.39        24
              Gujarat Lions       0.00      0.00      0.00         3
             Gujarat Titans       0.70      1.00      0.82         7
       Kochi Tuskers Kerala       0.00      0.00      0.00         1
      Kolkata Knight Riders       0.56      0.56      0.56        27
       Lucknow Super Giants       0.60      0.50      0.55         6
             Mumbai Indians       0.61      0.55      0.58        31
              Pune Warriors       0.00      0.00      0.00         2
               Punjab Kings       0.52      0.56      0.54        25
           Rajasthan Royals       0.50      0.70      0.58        23
     Rising Pune Supergiant       0.50      0.33      0.40         3
Royal Challengers Bangalore       0.48      0.52      0.50        27
        Sunrisers Hyderabad       0.50      0.44      0.47        25

                   accuracy                           0.52       233
                  macro avg       0.42      0.43      0.42       233
               weighted avg       0.50      0.52      0.51       233

In [26]:
import joblib

joblib.dump(model, "ipl_prediction_model.pkl")
joblib.dump(encoders, "ipl_feature_encoders.pkl")
joblib.dump(target_encoder, "ipl_target_encoder.pkl")

print("✅ Model files saved successfully!")

✅ Model files saved successfully!

In [27]:
def predict_winner(team1, team2, venue, toss_winner, toss_decision):

    input_data = pd.DataFrame({
        "TEAM1": [team1],
        "TEAM2": [team2],
        "VENUE": [venue],
        "TOSS_WINNER": [toss_winner],
        "TOSS_DECISION": [toss_decision]
    })

    # Encode input values
    for column in features:
        input_data[column] = encoders[column].transform(
            input_data[column].astype(str)
        )

    # Predict winner
    prediction = model.predict(input_data)[0]

    winner = target_encoder.inverse_transform([prediction])[0]

    # Prediction probability
    probabilities = model.predict_proba(input_data)[0]
    confidence = max(probabilities)

    return winner, confidence


print("✅ Prediction function created successfully!")

✅ Prediction function created successfully!

In [28]:
print("Teams:")
print(list(encoders["TEAM1"].classes_))

print("\nVenues:")
print(list(encoders["VENUE"].classes_))

print("\nToss decisions:")
print(list(encoders["TOSS_DECISION"].classes_))

Teams:
['Chennai Super Kings', 'Delhi Capitals', 'Gujarat Lions', 'Gujarat Titans', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Lucknow Super Giants', 'Mumbai Indians', 'Pune Warriors', 'Punjab Kings', 'Rajasthan Royals', 'Rising Pune Supergiant', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']

Venues:
['Arun Jaitley Stadium', 'Arun Jaitley Stadium, Delhi', 'Barabati Stadium', 'Barsapara Cricket Stadium, Guwahati', 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow', 'Brabourne Stadium', 'Brabourne Stadium, Mumbai', 'Buffalo Park', 'De Beers Diamond Oval', 'Dr DY Patil Sports Academy', 'Dr DY Patil Sports Academy, Mumbai', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium', 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam', 'Dubai International Cricket Stadium', 'Eden Gardens', 'Eden Gardens, Kolkata', 'Feroz Shah Kotla', 'Green Park', 'Himachal Pradesh Cricket Association Stadium', 'Himachal Pradesh Cricket Association Stadium, Dharamsala', 'Holkar Cricket Stadium', 'JSCA International Stadium Complex', 'Kingsmead', 'M Chinnaswamy Stadium', 'M Chinnaswamy Stadium, Bengaluru', 'M.Chinnaswamy Stadium', 'MA Chidambaram Stadium', 'MA Chidambaram Stadium, Chepauk', 'MA Chidambaram Stadium, Chepauk, Chennai', 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh', 'Maharashtra Cricket Association Stadium', 'Maharashtra Cricket Association Stadium, Pune', 'Narendra Modi Stadium, Ahmedabad', 'Nehru Stadium', 'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval', 'Punjab Cricket Association IS Bindra Stadium', 'Punjab Cricket Association IS Bindra Stadium, Mohali', 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh', 'Punjab Cricket Association Stadium, Mohali', 'Rajiv Gandhi International Stadium', 'Rajiv Gandhi International Stadium, Uppal', 'Rajiv Gandhi International Stadium, Uppal, Hyderabad', 'Sardar Patel Stadium, Motera', 'Saurashtra Cricket Association Stadium', 'Sawai Mansingh Stadium', 'Sawai Mansingh Stadium, Jaipur', 'Shaheed Veer Narayan Singh International Stadium', 'Sharjah Cricket Stadium', 'Sheikh Zayed Stadium', "St George's Park", 'Subrata Roy Sahara Stadium', 'SuperSport Park', 'Vidarbha Cricket Association Stadium, Jamtha', 'Wankhede Stadium', 'Wankhede Stadium, Mumbai', 'Zayed Cricket Stadium, Abu Dhabi']

Toss decisions:
['bat', 'field']

In [29]:
team1 = "Mumbai Indians"
team2 = "Chennai Super Kings"
venue = "Wankhede Stadium"
toss_winner = "Mumbai Indians"
toss_decision = "bat"

winner, confidence = predict_winner(
    team1,
    team2,
    venue,
    toss_winner,
    toss_decision
)

print("🏏 IPL MATCH PREDICTION")
print("-----------------------------")
print("Team 1       :", team1)
print("Team 2       :", team2)
print("Venue        :", venue)
print("Toss Winner  :", toss_winner)
print("Toss Decision:", toss_decision)
print("-----------------------------")
print("Predicted Winner:", winner)
print("Confidence      :", f"{confidence * 100:.2f}%")

🏏 IPL MATCH PREDICTION
-----------------------------
Team 1       : Mumbai Indians
Team 2       : Chennai Super Kings
Venue        : Wankhede Stadium
Toss Winner  : Mumbai Indians
Toss Decision: bat
-----------------------------
Predicted Winner: Mumbai Indians
Confidence      : 52.59%

In [30]:
def ipl_prediction_agent(
    team1,
    team2,
    venue,
    toss_winner,
    toss_decision
):
    try:
        winner, confidence = predict_winner(
            team1,
            team2,
            venue,
            toss_winner,
            toss_decision
        )

        return {
            "Team 1": team1,
            "Team 2": team2,
            "Venue": venue,
            "Toss Winner": toss_winner,
            "Toss Decision": toss_decision,
            "Predicted Winner": winner,
            "Confidence": f"{confidence * 100:.2f}%"
        }

    except Exception as e:
        return {
            "error": str(e)
        }


print("✅ IPL Prediction Agent created successfully!")

✅ IPL Prediction Agent created successfully!

In [31]:
result = ipl_prediction_agent(
    "Mumbai Indians",
    "Chennai Super Kings",
    "Wankhede Stadium",
    "Mumbai Indians",
    "bat"
)

print(result)

{'Team 1': 'Mumbai Indians', 'Team 2': 'Chennai Super Kings', 'Venue': 'Wankhede Stadium', 'Toss Winner': 'Mumbai Indians', 'Toss Decision': 'bat', 'Predicted Winner': 'Mumbai Indians', 'Confidence': '52.59%'}

In [32]:
!pip install -q gradio

In [33]:
import gradio as gr

# Get available values from the encoders
teams = list(encoders["TEAM1"].classes_)
venues = list(encoders["VENUE"].classes_)
toss_decisions = list(encoders["TOSS_DECISION"].classes_)


def predict_from_ui(team1, team2, venue, toss_winner, toss_decision):

    # Prevent selecting the same team
    if team1 == team2:
        return "⚠️ Team 1 and Team 2 must be different."

    result = ipl_prediction_agent(
        team1,
        team2,
        venue,
        toss_winner,
        toss_decision
    )

    if "error" in result:
        return f"❌ Error: {result['error']}"

    return f"""
🏏 IPL MATCH PREDICTION
━━━━━━━━━━━━━━━━━━━━━━━━

🏏 Team 1: {result['Team 1']}
🏏 Team 2: {result['Team 2']}

📍 Venue: {result['Venue']}

🪙 Toss Winner: {result['Toss Winner']}
🪙 Toss Decision: {result['Toss Decision']}

━━━━━━━━━━━━━━━━━━━━━━━━

🏆 Predicted Winner:
### {result['Predicted Winner']}

📊 Model Confidence:
### {result['Confidence']}
"""


with gr.Blocks(title="IPL Match Winner Predictor") as demo:

    gr.Markdown(
        """
        # 🏏 IPL Match Winner Predictor

        ### 🤖 Machine Learning Prediction System

        Enter the match details below to predict the winner.
        """
    )

    with gr.Row():

        team1 = gr.Dropdown(
            choices=teams,
            label="🏏 Team 1",
            value="Mumbai Indians"
        )

        team2 = gr.Dropdown(
            choices=teams,
            label="🏏 Team 2",
            value="Chennai Super Kings"
        )

    venue = gr.Dropdown(
        choices=venues,
        label="📍 Venue",
        value="Wankhede Stadium"
    )

    toss_winner = gr.Dropdown(
        choices=teams,
        label="🪙 Toss Winner",
        value="Mumbai Indians"
    )

    toss_decision = gr.Dropdown(
        choices=toss_decisions,
        label="🪙 Toss Decision",
        value="bat"
    )

    predict_button = gr.Button(
        "🔮 Predict Match Winner",
        variant="primary"
    )

    output = gr.Markdown(
        label="Prediction Result"
    )

    predict_button.click(
        fn=predict_from_ui,
        inputs=[
            team1,
            team2,
            venue,
            toss_winner,
            toss_decision
        ],
        outputs=output
    )


demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://1c72d2ab8d3309140c.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [35]:
def predict_from_ui(team1, team2, venue, toss_winner, toss_decision):

    if team1 == team2:
        return "⚠️ Team 1 and Team 2 must be different."

    try:
        input_data = pd.DataFrame({
            "TEAM1": [team1],
            "TEAM2": [team2],
            "VENUE": [venue],
            "TOSS_WINNER": [toss_winner],
            "TOSS_DECISION": [toss_decision]
        })

        # Encode input values
        for column in features:
            input_data[column] = encoders[column].transform(
                input_data[column].astype(str)
            )

        # Predict
        prediction = model.predict(input_data)[0]
        winner = target_encoder.inverse_transform([prediction])[0]

        # Get probabilities
        probabilities = model.predict_proba(input_data)[0]

        classes = list(target_encoder.classes_)

        team1_index = classes.index(team1)
        team2_index = classes.index(team2)

        team1_probability = probabilities[team1_index] * 100
        team2_probability = probabilities[team2_index] * 100

        return f"""
# 🏏 IPL MATCH PREDICTION

### {team1} 🆚 {team2}

**📍 Venue:** {venue}

**🪙 Toss Winner:** {toss_winner}

**🪙 Toss Decision:** {toss_decision}

---

## 🏆 Predicted Winner

# {winner}

### 📊 Prediction Probabilities

**{team1}:** {team1_probability:.2f}%

**{team2}:** {team2_probability:.2f}%

---

⚠️ *This is a machine-learning prediction and is not a guarantee of the actual match result.*
"""

    except Exception as e:
        return f"❌ Error: {str(e)}"


print("✅ Advanced prediction function created!")

✅ Advanced prediction function created!

In [36]:
import gradio as gr

with gr.Blocks(title="IPL Match Winner Predictor") as demo:

    gr.Markdown("""
    # 🏏 IPL Match Winner Predictor

    ### 🤖 AI/ML Based IPL Prediction System

    Predict the possible winner using team, venue and toss information.
    """)

    with gr.Row():

        team1 = gr.Dropdown(
            choices=teams,
            value="Mumbai Indians",
            label="🏏 Team 1"
        )

        team2 = gr.Dropdown(
            choices=teams,
            value="Chennai Super Kings",
            label="🏏 Team 2"
        )

    venue = gr.Dropdown(
        choices=venues,
        value="Wankhede Stadium",
        label="📍 Match Venue"
    )

    toss_winner = gr.Dropdown(
        choices=teams,
        value="Mumbai Indians",
        label="🪙 Toss Winner"
    )

    toss_decision = gr.Dropdown(
        choices=toss_decisions,
        value="bat",
        label="🪙 Toss Decision"
    )

    predict_button = gr.Button(
        "🔮 PREDICT MATCH WINNER",
        variant="primary"
    )

    output = gr.Markdown()

    predict_button.click(
        fn=predict_from_ui,
        inputs=[
            team1,
            team2,
            venue,
            toss_winner,
            toss_decision
        ],
        outputs=output
    )

demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://4674fc399f9b7b6a45.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)